name: msgpack2
description: MsgPack for Dart
version: 1.0.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- Dan Ellis <dan@danellis.me>
- Matthew Butler <butler.matthew@gmail.com>
homepage: https://github.com/butlermatt/msgpack2
environment:
  sdk: ">=1.13.0 <2.0.0"
dev_dependencies:
  test: ^0.12.0
